services:
  mysqldb:
    image: mysql:8.0.34
    volumes:
      - client-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Client_DB
      MYSQL_USER: NFFH_ADMIN
      MYSQL_PASSWORD: root
    ports:
    - "3306:3306"
    

  client-be:
    build:
      dockerfile: ./Dockerfile
      args:
        APP_NAME: nffh-client-BE
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: NFFH_ADMIN
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Client_DB 
    depends_on:
      - mysqldb
  

volumes:
  client-mysql-data:
      