version: '3.1'

services:

  mysqldb:
    image: mysql:8.0.34
    container_name: mysqldb   
    volumes:
      - client-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Client_DB
    networks:
        - internal

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: my-php-myadmin
      ports:
        - "8082:80"
      restart: always
      depends_on:
        - mysqldb
      environment:
        PMA_HOST: mysqldb
        PMA_USER: root
        PMA_PASSWORD: root

  client-be:
    container_name: client-be
    build:
      dockerfile: ./Dockerfile
      args:
        APP_NAME: nffh-client-BE
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/Client_DB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    networks:
      - gateway
      - internal

networks:
  gateway:
    external: true
    name: client-be
  internal:
    external: false
volumes:
  client-mysql-data:
      